name: genius_store
description: A comprehensive e-commerce mobile application built with Flutter and Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5

  # State Management
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5

  # Routing
  go_router: ^15.0.0

  # UI
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.3.1

  # Utilities
  intl: ^0.18.1
  logger: ^2.5.0
  dio: ^5.3.0
  shared_preferences: ^2.2.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  url_launcher: ^6.1.12
  path_provider: ^2.0.15
  flutter_secure_storage: ^10.0.0-beta.4
  connectivity_plus: ^6.1.3
  permission_handler: ^12.0.0+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  mockito: ^5.0.0
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/lang/
